set(_CATKIN_CURRENT_PACKAGE "rosilo_polaris_vega")
set(rosilo_polaris_vega_VERSION "0.0.0")
set(rosilo_polaris_vega_MAINTAINER "Murilo Marques Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_polaris_vega_PACKAGE_FORMAT "1")
set(rosilo_polaris_vega_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs" "geometry_msgs" "rosilo_conversions")
set(rosilo_polaris_vega_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "rosilo_conversions")
set(rosilo_polaris_vega_BUILDTOOL_DEPENDS "catkin")
set(rosilo_polaris_vega_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_polaris_vega_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "rosilo_conversions")
set(rosilo_polaris_vega_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "geometry_msgs" "rosilo_conversions")
set(rosilo_polaris_vega_TEST_DEPENDS )
set(rosilo_polaris_vega_DOC_DEPENDS )
set(rosilo_polaris_vega_URL_WEBSITE "")
set(rosilo_polaris_vega_URL_BUGTRACKER "")
set(rosilo_polaris_vega_URL_REPOSITORY "")
set(rosilo_polaris_vega_DEPRECATED "")