set(_CATKIN_CURRENT_PACKAGE "microscopic_image_capture")
set(microscopic_image_capture_VERSION "0.0.0")
set(microscopic_image_capture_MAINTAINER "yuki <yuki@todo.todo>")
set(microscopic_image_capture_PACKAGE_FORMAT "2")
set(microscopic_image_capture_BUILD_DEPENDS "OpenCV" "roscpp" "rospy" "std_msgs" "sensor_msgs" "robot_control")
set(microscopic_image_capture_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(microscopic_image_capture_BUILDTOOL_DEPENDS "catkin")
set(microscopic_image_capture_BUILDTOOL_EXPORT_DEPENDS )
set(microscopic_image_capture_EXEC_DEPENDS "OpenCV" "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(microscopic_image_capture_RUN_DEPENDS "OpenCV" "roscpp" "rospy" "std_msgs" "sensor_msgs")
set(microscopic_image_capture_TEST_DEPENDS )
set(microscopic_image_capture_DOC_DEPENDS )
set(microscopic_image_capture_URL_WEBSITE "")
set(microscopic_image_capture_URL_BUGTRACKER "")
set(microscopic_image_capture_URL_REPOSITORY "")
set(microscopic_image_capture_DEPRECATED "")