set(_CATKIN_CURRENT_PACKAGE "rosilo_clock")
set(rosilo_clock_VERSION "0.0.0")
set(rosilo_clock_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_clock_PACKAGE_FORMAT "1")
set(rosilo_clock_BUILD_DEPENDS "roscpp" "rospy")
set(rosilo_clock_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(rosilo_clock_BUILDTOOL_DEPENDS "catkin")
set(rosilo_clock_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_clock_EXEC_DEPENDS "roscpp" "rospy")
set(rosilo_clock_RUN_DEPENDS "roscpp" "rospy")
set(rosilo_clock_TEST_DEPENDS )
set(rosilo_clock_DOC_DEPENDS )
set(rosilo_clock_URL_WEBSITE "")
set(rosilo_clock_URL_BUGTRACKER "")
set(rosilo_clock_URL_REPOSITORY "")
set(rosilo_clock_DEPRECATED "")