set(_CATKIN_CURRENT_PACKAGE "robot_control")
set(robot_control_VERSION "0.0.0")
set(robot_control_MAINTAINER "christian yuen <christiantomuyuen@g.ecc.u-tokyo.ac.jp>")
set(robot_control_PACKAGE_FORMAT "2")
set(robot_control_BUILD_DEPENDS "message_generation" "rosilo_robot_kinematics" "rosilo_robot_driver" "rosilo_robot_driver_denso" "rosilo_conversions" "rosilo_clock" "roscpp" "rospy" "std_msgs" "sensor_msgs" "rosilo_datalogger" "sas_operator_side_receiver" "sas_robot_kinematics" "sas_robot_driver" "sas_robot_driver_denso" "sas_conversions" "sas_clock" "sas_common" "sas_datalogger" "sas_operator_side_receiver" "vitreoretinal_kinematics")
set(robot_control_BUILD_EXPORT_DEPENDS "rosilo_robot_kinematics" "rosilo_robot_driver" "rosilo_robot_driver_denso" "rosilo_conversions" "rosilo_clock" "roscpp" "rospy" "rosilo_datalogger" "sas_operator_side_receiver" "sas_robot_kinematics" "sas_robot_driver" "sas_robot_driver_denso" "sas_conversions" "sas_clock" "sas_common" "sas_datalogger" "sas_operator_side_receiver" "vitreoretinal_kinematics")
set(robot_control_BUILDTOOL_DEPENDS "catkin")
set(robot_control_BUILDTOOL_EXPORT_DEPENDS )
set(robot_control_EXEC_DEPENDS "message_runtime" "rosilo_robot_kinematics" "rosilo_robot_driver" "rosilo_robot_driver_denso" "rosilo_conversions" "rosilo_clock" "roscpp" "rospy" "std_msgs" "sensor_msgs" "rosilo_datalogger" "sas_operator_side_receiver" "sas_robot_kinematics" "sas_robot_driver" "sas_robot_driver_denso" "sas_conversions" "sas_clock" "sas_common" "roscpp" "rospy" "sas_datalogger" "sas_operator_side_receiver" "vitreoretinal_kinematics")
set(robot_control_RUN_DEPENDS "message_runtime" "rosilo_robot_kinematics" "rosilo_robot_driver" "rosilo_robot_driver_denso" "rosilo_conversions" "rosilo_clock" "roscpp" "rospy" "std_msgs" "sensor_msgs" "rosilo_datalogger" "sas_operator_side_receiver" "sas_robot_kinematics" "sas_robot_driver" "sas_robot_driver_denso" "sas_conversions" "sas_clock" "sas_common" "sas_datalogger" "vitreoretinal_kinematics")
set(robot_control_TEST_DEPENDS )
set(robot_control_DOC_DEPENDS )
set(robot_control_URL_WEBSITE "")
set(robot_control_URL_BUGTRACKER "")
set(robot_control_URL_REPOSITORY "")
set(robot_control_DEPRECATED "")