set(_CATKIN_CURRENT_PACKAGE "sas_camera_driver_decklink")
set(sas_camera_driver_decklink_VERSION "0.0.0")
set(sas_camera_driver_decklink_MAINTAINER "nml <nml@todo.todo>")
set(sas_camera_driver_decklink_PACKAGE_FORMAT "2")
set(sas_camera_driver_decklink_BUILD_DEPENDS "image_transport" "cv_bridge" "roscpp" "rospy")
set(sas_camera_driver_decklink_BUILD_EXPORT_DEPENDS "image_transport" "cv_bridge" "roscpp" "rospy")
set(sas_camera_driver_decklink_BUILDTOOL_DEPENDS "catkin")
set(sas_camera_driver_decklink_BUILDTOOL_EXPORT_DEPENDS )
set(sas_camera_driver_decklink_EXEC_DEPENDS "image_transport" "cv_bridge" "roscpp" "rospy")
set(sas_camera_driver_decklink_RUN_DEPENDS "image_transport" "cv_bridge" "roscpp" "rospy")
set(sas_camera_driver_decklink_TEST_DEPENDS )
set(sas_camera_driver_decklink_DOC_DEPENDS )
set(sas_camera_driver_decklink_URL_WEBSITE "")
set(sas_camera_driver_decklink_URL_BUGTRACKER "")
set(sas_camera_driver_decklink_URL_REPOSITORY "")
set(sas_camera_driver_decklink_DEPRECATED "")