set(_CATKIN_CURRENT_PACKAGE "robot_calibration")
set(robot_calibration_VERSION "0.0.0")
set(robot_calibration_MAINTAINER "qlin1806 <qlin1806m@gmail.com>")
set(robot_calibration_PACKAGE_FORMAT "2")
set(robot_calibration_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "robot_control")
set(robot_calibration_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "robot_control")
set(robot_calibration_BUILDTOOL_DEPENDS "catkin")
set(robot_calibration_BUILDTOOL_EXPORT_DEPENDS )
set(robot_calibration_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "robot_control")
set(robot_calibration_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "robot_control")
set(robot_calibration_TEST_DEPENDS )
set(robot_calibration_DOC_DEPENDS )
set(robot_calibration_URL_WEBSITE "")
set(robot_calibration_URL_BUGTRACKER "")
set(robot_calibration_URL_REPOSITORY "")
set(robot_calibration_DEPRECATED "")