devel_space: /home/yuki/git/ctyuen2022/catkin_ws/devel_release
install: false
install_space: /home/yuki/git/ctyuen2022/catkin_ws/install_release
profile: release
source_space: /home/yuki/git/ctyuen2022/catkin_ws/src
workspace: /home/yuki/git/ctyuen2022/catkin_ws
