set(_CATKIN_CURRENT_PACKAGE "rosilo_robot_driver_denso")
set(rosilo_robot_driver_denso_VERSION "0.0.0")
set(rosilo_robot_driver_denso_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_robot_driver_denso_PACKAGE_FORMAT "1")
set(rosilo_robot_driver_denso_BUILD_DEPENDS "roscpp" "rospy" "rosilo_clock" "rosilo_robot_driver")
set(rosilo_robot_driver_denso_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "rosilo_clock" "rosilo_robot_driver")
set(rosilo_robot_driver_denso_BUILDTOOL_DEPENDS "catkin")
set(rosilo_robot_driver_denso_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_robot_driver_denso_EXEC_DEPENDS "roscpp" "rospy" "rosilo_clock" "rosilo_robot_driver")
set(rosilo_robot_driver_denso_RUN_DEPENDS "roscpp" "rospy" "rosilo_clock" "rosilo_robot_driver")
set(rosilo_robot_driver_denso_TEST_DEPENDS )
set(rosilo_robot_driver_denso_DOC_DEPENDS )
set(rosilo_robot_driver_denso_URL_WEBSITE "")
set(rosilo_robot_driver_denso_URL_BUGTRACKER "")
set(rosilo_robot_driver_denso_URL_REPOSITORY "")
set(rosilo_robot_driver_denso_DEPRECATED "")