set(_CATKIN_CURRENT_PACKAGE "rosilo_conversions")
set(rosilo_conversions_VERSION "0.0.0")
set(rosilo_conversions_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_conversions_PACKAGE_FORMAT "2")
set(rosilo_conversions_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(rosilo_conversions_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(rosilo_conversions_BUILDTOOL_DEPENDS "catkin")
set(rosilo_conversions_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_conversions_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(rosilo_conversions_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "std_msgs")
set(rosilo_conversions_TEST_DEPENDS )
set(rosilo_conversions_DOC_DEPENDS )
set(rosilo_conversions_URL_WEBSITE "")
set(rosilo_conversions_URL_BUGTRACKER "")
set(rosilo_conversions_URL_REPOSITORY "")
set(rosilo_conversions_DEPRECATED "")