// Generated by gencpp from file robot_control/ImgShowMsg.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_IMGSHOWMSG_H
#define ROBOT_CONTROL_MESSAGE_IMGSHOWMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_control
{
template <class ContainerAllocator>
struct ImgShowMsg_
{
  typedef ImgShowMsg_<ContainerAllocator> Type;

  ImgShowMsg_()
    : header()
    , value()  {
    }
  ImgShowMsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::robot_control::ImgShowMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::ImgShowMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ImgShowMsg_

typedef ::robot_control::ImgShowMsg_<std::allocator<void> > ImgShowMsg;

typedef boost::shared_ptr< ::robot_control::ImgShowMsg > ImgShowMsgPtr;
typedef boost::shared_ptr< ::robot_control::ImgShowMsg const> ImgShowMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::ImgShowMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::ImgShowMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::ImgShowMsg_<ContainerAllocator1> & lhs, const ::robot_control::ImgShowMsg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::ImgShowMsg_<ContainerAllocator1> & lhs, const ::robot_control::ImgShowMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::ImgShowMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::ImgShowMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::ImgShowMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::ImgShowMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::ImgShowMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::ImgShowMsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::ImgShowMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a71211f536b88e615f1efe03e6e15cf2";
  }

  static const char* value(const ::robot_control::ImgShowMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa71211f536b88e61ULL;
  static const uint64_t static_value2 = 0x5f1efe03e6e15cf2ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::ImgShowMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/ImgShowMsg";
  }

  static const char* value(const ::robot_control::ImgShowMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::ImgShowMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] value\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_control::ImgShowMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::ImgShowMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImgShowMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::ImgShowMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::ImgShowMsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_IMGSHOWMSG_H
