// Generated by gencpp from file robot_control/ROI.msg
// DO NOT EDIT!


#ifndef ROBOT_CONTROL_MESSAGE_ROI_H
#define ROBOT_CONTROL_MESSAGE_ROI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace robot_control
{
template <class ContainerAllocator>
struct ROI_
{
  typedef ROI_<ContainerAllocator> Type;

  ROI_()
    : roi_image()
    , roi_values()  {
    }
  ROI_(const ContainerAllocator& _alloc)
    : roi_image(_alloc)
    , roi_values(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _roi_image_type;
  _roi_image_type roi_image;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _roi_values_type;
  _roi_values_type roi_values;





  typedef boost::shared_ptr< ::robot_control::ROI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_control::ROI_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_

typedef ::robot_control::ROI_<std::allocator<void> > ROI;

typedef boost::shared_ptr< ::robot_control::ROI > ROIPtr;
typedef boost::shared_ptr< ::robot_control::ROI const> ROIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_control::ROI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_control::ROI_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_control::ROI_<ContainerAllocator1> & lhs, const ::robot_control::ROI_<ContainerAllocator2> & rhs)
{
  return lhs.roi_image == rhs.roi_image &&
    lhs.roi_values == rhs.roi_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_control::ROI_<ContainerAllocator1> & lhs, const ::robot_control::ROI_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_control::ROI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_control::ROI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_control::ROI_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::ROI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_control::ROI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_control::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4345e91a8d0d0f4b5b72c6369217bad9";
  }

  static const char* value(const ::robot_control::ROI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4345e91a8d0d0f4bULL;
  static const uint64_t static_value2 = 0x5b72c6369217bad9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_control::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_control/ROI";
  }

  static const char* value(const ::robot_control::ROI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_control::ROI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image roi_image\n"
"\n"
"float64[] roi_values\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_control::ROI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_control::ROI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roi_image);
      stream.next(m.roi_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_control::ROI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_control::ROI_<ContainerAllocator>& v)
  {
    s << indent << "roi_image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.roi_image);
    s << indent << "roi_values[]" << std::endl;
    for (size_t i = 0; i < v.roi_values.size(); ++i)
    {
      s << indent << "  roi_values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.roi_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_CONTROL_MESSAGE_ROI_H
