set(_CATKIN_CURRENT_PACKAGE "rosilo_robot_kinematics")
set(rosilo_robot_kinematics_VERSION "0.0.0")
set(rosilo_robot_kinematics_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_robot_kinematics_PACKAGE_FORMAT "2")
set(rosilo_robot_kinematics_BUILD_DEPENDS "rosilo_conversions" "geometry_msgs" "roscpp" "rospy")
set(rosilo_robot_kinematics_BUILD_EXPORT_DEPENDS "rosilo_conversions" "geometry_msgs" "roscpp" "rospy")
set(rosilo_robot_kinematics_BUILDTOOL_DEPENDS "catkin")
set(rosilo_robot_kinematics_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_robot_kinematics_EXEC_DEPENDS "rosilo_conversions" "geometry_msgs" "roscpp" "rospy")
set(rosilo_robot_kinematics_RUN_DEPENDS "rosilo_conversions" "geometry_msgs" "roscpp" "rospy")
set(rosilo_robot_kinematics_TEST_DEPENDS )
set(rosilo_robot_kinematics_DOC_DEPENDS )
set(rosilo_robot_kinematics_URL_WEBSITE "")
set(rosilo_robot_kinematics_URL_BUGTRACKER "")
set(rosilo_robot_kinematics_URL_REPOSITORY "")
set(rosilo_robot_kinematics_DEPRECATED "")