set(rosilo_robot_kinematics_SETUP_PY_SETUP_MODULE "distutils.core")
set(rosilo_robot_kinematics_SETUP_PY_VERSION "0.0.0")
set(rosilo_robot_kinematics_SETUP_PY_SCRIPTS "")
set(rosilo_robot_kinematics_SETUP_PY_PACKAGES "rosilo_robot_kinematics")
set(rosilo_robot_kinematics_SETUP_PY_PACKAGE_DIRS "src/rosilo_robot_kinematics")
set(rosilo_robot_kinematics_SETUP_PY_MODULES "")
set(rosilo_robot_kinematics_SETUP_PY_MODULE_DIRS "")