// Generated by gencpp from file rosilo_datalogger/SaveRequest.msg
// DO NOT EDIT!


#ifndef ROSILO_DATALOGGER_MESSAGE_SAVEREQUEST_H
#define ROSILO_DATALOGGER_MESSAGE_SAVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosilo_datalogger
{
template <class ContainerAllocator>
struct SaveRequest_
{
  typedef SaveRequest_<ContainerAllocator> Type;

  SaveRequest_()
    : filename()  {
    }
  SaveRequest_(const ContainerAllocator& _alloc)
    : filename(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _filename_type;
  _filename_type filename;





  typedef boost::shared_ptr< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveRequest_

typedef ::rosilo_datalogger::SaveRequest_<std::allocator<void> > SaveRequest;

typedef boost::shared_ptr< ::rosilo_datalogger::SaveRequest > SaveRequestPtr;
typedef boost::shared_ptr< ::rosilo_datalogger::SaveRequest const> SaveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosilo_datalogger::SaveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rosilo_datalogger::SaveRequest_<ContainerAllocator1> & lhs, const ::rosilo_datalogger::SaveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.filename == rhs.filename;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rosilo_datalogger::SaveRequest_<ContainerAllocator1> & lhs, const ::rosilo_datalogger::SaveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rosilo_datalogger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "030824f52a0628ead956fb9d67e66ae9";
  }

  static const char* value(const ::rosilo_datalogger::SaveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x030824f52a0628eaULL;
  static const uint64_t static_value2 = 0xd956fb9d67e66ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosilo_datalogger/SaveRequest";
  }

  static const char* value(const ::rosilo_datalogger::SaveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filename\n"
;
  }

  static const char* value(const ::rosilo_datalogger::SaveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filename);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosilo_datalogger::SaveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosilo_datalogger::SaveRequest_<ContainerAllocator>& v)
  {
    s << indent << "filename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.filename);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSILO_DATALOGGER_MESSAGE_SAVEREQUEST_H
