// Generated by gencpp from file rosilo_datalogger/Save.msg
// DO NOT EDIT!


#ifndef ROSILO_DATALOGGER_MESSAGE_SAVE_H
#define ROSILO_DATALOGGER_MESSAGE_SAVE_H

#include <ros/service_traits.h>


#include <rosilo_datalogger/SaveRequest.h>
#include <rosilo_datalogger/SaveResponse.h>


namespace rosilo_datalogger
{

struct Save
{

typedef SaveRequest Request;
typedef SaveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Save
} // namespace rosilo_datalogger


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosilo_datalogger::Save > {
  static const char* value()
  {
    return "86a64704c03f5415ea7ff59624fa3411";
  }

  static const char* value(const ::rosilo_datalogger::Save&) { return value(); }
};

template<>
struct DataType< ::rosilo_datalogger::Save > {
  static const char* value()
  {
    return "rosilo_datalogger/Save";
  }

  static const char* value(const ::rosilo_datalogger::Save&) { return value(); }
};


// service_traits::MD5Sum< ::rosilo_datalogger::SaveRequest> should match
// service_traits::MD5Sum< ::rosilo_datalogger::Save >
template<>
struct MD5Sum< ::rosilo_datalogger::SaveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosilo_datalogger::Save >::value();
  }
  static const char* value(const ::rosilo_datalogger::SaveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosilo_datalogger::SaveRequest> should match
// service_traits::DataType< ::rosilo_datalogger::Save >
template<>
struct DataType< ::rosilo_datalogger::SaveRequest>
{
  static const char* value()
  {
    return DataType< ::rosilo_datalogger::Save >::value();
  }
  static const char* value(const ::rosilo_datalogger::SaveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosilo_datalogger::SaveResponse> should match
// service_traits::MD5Sum< ::rosilo_datalogger::Save >
template<>
struct MD5Sum< ::rosilo_datalogger::SaveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosilo_datalogger::Save >::value();
  }
  static const char* value(const ::rosilo_datalogger::SaveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosilo_datalogger::SaveResponse> should match
// service_traits::DataType< ::rosilo_datalogger::Save >
template<>
struct DataType< ::rosilo_datalogger::SaveResponse>
{
  static const char* value()
  {
    return DataType< ::rosilo_datalogger::Save >::value();
  }
  static const char* value(const ::rosilo_datalogger::SaveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSILO_DATALOGGER_MESSAGE_SAVE_H
