set(_CATKIN_CURRENT_PACKAGE "rosilo_datalogger")
set(rosilo_datalogger_VERSION "0.0.0")
set(rosilo_datalogger_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_datalogger_PACKAGE_FORMAT "1")
set(rosilo_datalogger_BUILD_DEPENDS "message_generation" "roscpp" "rospy" "std_msgs")
set(rosilo_datalogger_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(rosilo_datalogger_BUILDTOOL_DEPENDS "catkin")
set(rosilo_datalogger_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_datalogger_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(rosilo_datalogger_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "message_runtime")
set(rosilo_datalogger_TEST_DEPENDS )
set(rosilo_datalogger_DOC_DEPENDS )
set(rosilo_datalogger_URL_WEBSITE "http://github.com/rosilo")
set(rosilo_datalogger_URL_BUGTRACKER "")
set(rosilo_datalogger_URL_REPOSITORY "")
set(rosilo_datalogger_DEPRECATED "")