set(_CATKIN_CURRENT_PACKAGE "rosilo_robot_driver")
set(rosilo_robot_driver_VERSION "0.0.0")
set(rosilo_robot_driver_MAINTAINER "Murilo M. Marinho <murilo@nml.t.u-tokyo.ac.jp>")
set(rosilo_robot_driver_PACKAGE_FORMAT "1")
set(rosilo_robot_driver_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "rosilo_conversions")
set(rosilo_robot_driver_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "rospy" "rosilo_conversions")
set(rosilo_robot_driver_BUILDTOOL_DEPENDS "catkin")
set(rosilo_robot_driver_BUILDTOOL_EXPORT_DEPENDS )
set(rosilo_robot_driver_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "rospy" "rosilo_conversions")
set(rosilo_robot_driver_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "rosilo_conversions")
set(rosilo_robot_driver_TEST_DEPENDS )
set(rosilo_robot_driver_DOC_DEPENDS )
set(rosilo_robot_driver_URL_WEBSITE "")
set(rosilo_robot_driver_URL_BUGTRACKER "")
set(rosilo_robot_driver_URL_REPOSITORY "")
set(rosilo_robot_driver_DEPRECATED "")